// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhawsdrsaqecdmcawgms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYXdzZHJzYXFlY2RtY2F3Z21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTU2MjksImV4cCI6MjA2NjkzMTYyOX0.crWWa3WWiOaDi3fRkeQzd70blIyF0mwe_RP4Xadc1vQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});